package say

// A line to a language. Forms of a number are parted by a bar and take the
// place of a hash: English and French have two, Russian three.
var words = map[string]map[string]string{
	English: {
		"lead.reporting":  "Reporting",
		"lead.nothing":    "Nothing reported yet",
		"lead.silent":     "Nothing reported since ",
		"lead.card.on":    ", card on",
		"lead.card.off":   ", card off",
		"lead.kept":       ", # play kept.|, # plays kept.",
		"start.title":     "Two things to do",
		"start.extension": "Install the extension.",
		"start.how":       "Chrome → Extensions → Developer mode → Load unpacked → the extension folder. Nothing is written down until it does.",
		"start.discord":   "Connect Discord",
		"start.why":       "if you want friends to see what plays. It is optional, and off until you do — the box is",
		"start.where":     "at the foot of the page",
		"week":            "This week",
		"month":           "This month",
		"all":             "All of it",
		"show.month":      "the month",
		"show.week":       "the week",
		"show.all":        "all of it",
		"show":            "show ",
		"times":           "# time|# times",
		"uncounted":       "# still uncounted: a play is closed by the next one.",
		"plays":           "Plays",
		"find":            "find a name",
		"find.do":         "Find",
		"find.all":        "the lot",
		"find.nothing":    "Nothing by that name.",
		"nothing":         "Nothing yet. Install the extension and open a video.",
		"today":           "Today",
		"yesterday":       "Yesterday",
		"playing":         "playing",
		"paused":          "paused",
		"forget":          "Forget this one",
		"more":            "# more|# more",
		"older":           "# older in the file",
		"spreadsheet":     "spreadsheet",
		"settings":        "settings",
		"settings.title":  "Settings",
		"discord":         "Discord",
		"discord.what":    "What plays goes on your Discord profile, where friends see it. A number of your own only changes the name Discord writes above the card and the pictures on it.",
		"discord.number":  "The number comes from",
		"discord.how":     ": New Application, then General Information, then Application ID. Discord itself has to be the desktop one, and open.",
		"connect":         "Connect",
		"disconnect":      "Disconnect",
		"card":            "On the card",
		"card.what":       "Everything netwatch knows how to recognise. Unticked ones stay out of Discord; the list keeps them either way.",
		"save":            "Save",
		"kind.Video":      "Video",
		"kind.Streams":    "Streams",
		"kind.Films":      "Films",
		"kind.Music":      "Music",
		"kind.Yours":      "Yours",
		"site":            "Add a site",
		"site.what":       "Anything with a video or a sound on it. netwatch cannot read a strange address, so it asks the page instead — which is how it knows what Yandex Music is playing.",
		"site.browser":    "The browser has to be asked separately, and only you can ask it: right click the netwatch icon in the toolbar, Options, then Allow beside the site. Until then netwatch knows the site and nothing reports from it.",
		"site.name":       "name",
		"add":             "Add",
		"starting":        "Starting",
		"starting.what":   "A list keeps itself only while something is keeping it.",
		"starting.on":     "Start with Windows",
		"starting.off":    "Do not start with Windows",
		"language":        "Language",
		"quit":            "Quit netwatch",
		"gone.title":      "netwatch has stopped",
		"gone.what":       "Nothing is being written down, and the Discord card is down.",
		"gone.again":      "Start it again whenever. The list is where it was.",
		"sec":             "# sec",
		"min":             "# min",
		"hour":            "# h",
	},

	Russian: {
		"lead.reporting":  "Докладывает",
		"lead.nothing":    "Пока ничего не доложено",
		"lead.silent":     "Молчит с ",
		"lead.card.on":    ", карточка включена",
		"lead.card.off":   ", карточка выключена",
		"lead.kept":       ", # просмотр в списке.|, # просмотра в списке.|, # просмотров в списке.",
		"start.title":     "Осталось два шага",
		"start.extension": "Поставьте расширение.",
		"start.how":       "Chrome → Расширения → Режим разработчика → Загрузить распакованное → папка extension. Пока его нет, ничего не записывается.",
		"start.discord":   "Подключите Discord",
		"start.why":       "если хотите, чтобы друзья видели, что играет. Необязательно, и выключено, пока не подключите — поле",
		"start.where":     "внизу страницы",
		"week":            "За неделю",
		"month":           "За месяц",
		"all":             "За всё время",
		"show.month":      "месяц",
		"show.week":       "неделю",
		"show.all":        "всё время",
		"show":            "показать ",
		"times":           "# раз|# раза|# раз",
		"uncounted":       "# ещё не сосчитан: просмотр закрывается следующим.",
		"plays":           "Просмотры",
		"find":            "найти по названию",
		"find.do":         "Найти",
		"find.all":        "всё",
		"find.nothing":    "По этому названию ничего нет.",
		"nothing":         "Пока пусто. Поставьте расширение и откройте видео.",
		"today":           "Сегодня",
		"yesterday":       "Вчера",
		"playing":         "идёт",
		"paused":          "пауза",
		"forget":          "Забыть этот",
		"more":            "ещё #|ещё #|ещё #",
		"older":           "# ещё в файле",
		"spreadsheet":     "таблица",
		"settings":        "настройки",
		"settings.title":  "Настройки",
		"discord":         "Discord",
		"discord.what":    "То, что играет, показывается в вашем профиле Discord, где это видят друзья. Свой номер меняет только имя над карточкой и картинки на ней.",
		"discord.number":  "Номер берётся тут:",
		"discord.how":     " New Application, потом General Information, потом Application ID. Сам Discord должен быть настольным и открытым.",
		"connect":         "Подключить",
		"disconnect":      "Отключить",
		"card":            "На карточке",
		"card.what":       "Всё, что netwatch умеет узнавать. Снятые не попадают в Discord; в список они пишутся всё равно.",
		"save":            "Сохранить",
		"kind.Video":      "Видео",
		"kind.Streams":    "Стримы",
		"kind.Films":      "Кино",
		"kind.Music":      "Музыка",
		"kind.Yours":      "Свои",
		"site":            "Добавить сайт",
		"site.what":       "Любой, где есть видео или звук. Чужой адрес netwatch прочитать не может, поэтому спрашивает саму страницу — так же, как узнаёт, что играет в Яндекс.Музыке.",
		"site.browser":    "Браузер придётся попросить отдельно, и попросить можете только вы: правый щелчок по значку netwatch, Параметры, потом Allow рядом с сайтом. До этого netwatch сайт знает, а докладывать о нём некому.",
		"site.name":       "имя",
		"add":             "Добавить",
		"starting":        "Запуск",
		"starting.what":   "Список ведётся, только пока есть кому его вести.",
		"starting.on":     "Запускать с Windows",
		"starting.off":    "Не запускать с Windows",
		"language":        "Язык",
		"quit":            "Закрыть netwatch",
		"gone.title":      "netwatch остановлен",
		"gone.what":       "Ничего не записывается, карточка в Discord снята.",
		"gone.again":      "Запустите снова когда захотите. Список на месте.",
		"sec":             "# сек",
		"min":             "# мин",
		"hour":            "# ч",
	},

	French: {
		"lead.reporting":  "Rapporte",
		"lead.nothing":    "Rien de rapporté pour l'instant",
		"lead.silent":     "Silencieux depuis le ",
		"lead.card.on":    ", carte active",
		"lead.card.off":   ", carte inactive",
		"lead.kept":       ", # lecture gardée.|, # lectures gardées.",
		"start.title":     "Deux choses à faire",
		"start.extension": "Installez l'extension.",
		"start.how":       "Chrome → Extensions → Mode développeur → Charger l'extension non empaquetée → le dossier extension. Rien n'est noté tant qu'elle n'est pas là.",
		"start.discord":   "Connectez Discord",
		"start.why":       "si vous voulez que vos amis voient ce qui joue. C'est facultatif, et inactif tant que vous ne le faites pas — le champ est",
		"start.where":     "au bas de la page",
		"week":            "Cette semaine",
		"month":           "Ce mois",
		"all":             "Tout",
		"show.month":      "le mois",
		"show.week":       "la semaine",
		"show.all":        "tout",
		"show":            "montrer ",
		"times":           "# fois|# fois",
		"uncounted":       "# pas encore compté : une lecture se ferme avec la suivante.",
		"plays":           "Lectures",
		"find":            "chercher un nom",
		"find.do":         "Chercher",
		"find.all":        "tout",
		"find.nothing":    "Rien à ce nom.",
		"nothing":         "Rien pour l'instant. Installez l'extension et ouvrez une vidéo.",
		"today":           "Aujourd'hui",
		"yesterday":       "Hier",
		"playing":         "en cours",
		"paused":          "en pause",
		"forget":          "Oublier celle-ci",
		"more":            "# de plus|# de plus",
		"older":           "# de plus dans le fichier",
		"spreadsheet":     "tableur",
		"settings":        "réglages",
		"settings.title":  "Réglages",
		"discord":         "Discord",
		"discord.what":    "Ce qui joue apparaît sur votre profil Discord, où vos amis le voient. Un numéro à vous ne change que le nom écrit au-dessus de la carte et les images dessus.",
		"discord.number":  "Le numéro vient de",
		"discord.how":     " : New Application, puis General Information, puis Application ID. Discord lui-même doit être celui du bureau, et ouvert.",
		"connect":         "Connecter",
		"disconnect":      "Déconnecter",
		"card":            "Sur la carte",
		"card.what":       "Tout ce que netwatch sait reconnaître. Les cases décochées ne vont pas dans Discord ; la liste les garde quand même.",
		"save":            "Enregistrer",
		"kind.Video":      "Vidéo",
		"kind.Streams":    "Direct",
		"kind.Films":      "Films",
		"kind.Music":      "Musique",
		"kind.Yours":      "À vous",
		"site":            "Ajouter un site",
		"site.what":       "N'importe lequel avec une vidéo ou un son. netwatch ne sait pas lire une adresse inconnue, alors il demande à la page — c'est ainsi qu'il sait ce que joue Yandex Music.",
		"site.browser":    "Il faut demander au navigateur séparément, et vous seul pouvez le faire : clic droit sur l'icône netwatch, Options, puis Allow à côté du site. Avant cela netwatch connaît le site et personne ne lui rapporte rien.",
		"site.name":       "nom",
		"add":             "Ajouter",
		"starting":        "Démarrage",
		"starting.what":   "Une liste ne se tient que tant que quelque chose la tient.",
		"starting.on":     "Démarrer avec Windows",
		"starting.off":    "Ne pas démarrer avec Windows",
		"language":        "Langue",
		"quit":            "Fermer netwatch",
		"gone.title":      "netwatch est arrêté",
		"gone.what":       "Plus rien n'est noté, et la carte Discord est retirée.",
		"gone.again":      "Relancez-le quand vous voulez. La liste est là où elle était.",
		"sec":             "# s",
		"min":             "# min",
		"hour":            "# h",
	},
}
